name: Deploy Knowledge Base

on:
  push:
    branches:
      - main # Executa sempre que a main for atualizada

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Instalar MkDocs
        run: pip install mkdocs
        
      - name: Publicar no GitHub Pages
        run: mkdocs gh-deploy --force