
SET SQL DIALECT 3; 

/* CREATE DATABASE '127.0.0.1/3055:D:\DataBases\TesteAutomatizado\TESTEAUTOMATIZADOMC.FDB' PAGE_SIZE 16384 DEFAULT CHARACTER SET ISO8859_1; */


/*  Generators or sequences */
CREATE GENERATOR GEN_AREA START WITH 1;
CREATE GENERATOR GEN_CAM_EXECUTAVEIS START WITH 1;
CREATE GENERATOR GEN_CASO_TESTE START WITH 1;
CREATE GENERATOR GEN_CASO_TESTE_EXECUCAO_ID START WITH 1;
CREATE GENERATOR GEN_MODULO START WITH 1;
CREATE GENERATOR GEN_UNIT START WITH 1;
CREATE GENERATOR GEN_VERSAO START WITH 1;

/* Domain definitions */
CREATE DOMAIN AUTOINC AS BIGINT NOT NULL;
CREATE DOMAIN AUTOINCREMENTO AS BIGINT NOT NULL;
CREATE DOMAIN DATA AS DATE;
CREATE DOMAIN DATA_HORA AS TIMESTAMP;
CREATE DOMAIN DESCRICAO AS VARCHAR(60) NOT NULL;
CREATE DOMAIN DINHEIRO AS NUMERIC(18, 4) NOT NULL;
CREATE DOMAIN ESTOQUE AS NUMERIC(18, 6) NOT NULL;
CREATE DOMAIN "ESTOQUE(4)" AS NUMERIC(18, 4) NOT NULL;
CREATE DOMAIN HORA AS TIME;
CREATE DOMAIN JSON AS BLOB SUB_TYPE 0 SEGMENT SIZE 100;
CREATE DOMAIN LOGICO AS CHAR(1)
         DEFAULT 'N' NOT NULL;
CREATE DOMAIN STRING255 AS VARCHAR(255);
CREATE DOMAIN STRING40 AS VARCHAR(40);
CREATE DOMAIN STRING50 AS VARCHAR(50);
CREATE DOMAIN TEXTO AS BLOB SUB_TYPE TEXT SEGMENT SIZE 100;
COMMIT WORK;

/* Table: AREA, Owner: SYSDBA */
CREATE TABLE AREA (AUTOINC_AREA AUTOINC,
        DESCRICAO_AREA STRING50,
        MODULO_AREA AUTOINC,
CONSTRAINT PK_AREA PRIMARY KEY (AUTOINC_AREA));

/* Table: CAMINHO_EXECUTAVEIS, Owner: SYSDBA */
CREATE TABLE CAMINHO_EXECUTAVEIS (CODIGO_CAMINHO_EXE AUTOINC NOT NULL,
        DESCRICAO_CAMINHO_EXE STRING40,
        CAMINHOCOMPLETO_CAMINHO_EXE STRING255,
        BASEDADOS_CAMINHO_EXE STRING255,
        USUARIO STRING50,
        SENHA STRING50,
CONSTRAINT PK_CAMINHO_EXECUTAVEIS PRIMARY KEY (CODIGO_CAMINHO_EXE));

/* Table: CASO_TESTE, Owner: SYSDBA */
CREATE TABLE CASO_TESTE (AUTOINC_CT AUTOINC NOT NULL,
        MODULO_CT AUTOINC NOT NULL,
        AREA_CT AUTOINC,
        DESCRICAO_CASO_TESTE_CT STRING255 NOT NULL,
        CASO_TESTE_CT BLOB SUB_TYPE 0 SEGMENT SIZE 100,
        CAMPOS_DISPONIVEIS_CT BLOB SUB_TYPE 0 SEGMENT SIZE 100,
        RESULTADO_ESPERADO_CT BLOB SUB_TYPE 0 SEGMENT SIZE 100,
        ATIVO_CT LOGICO DEFAULT 'S' NOT NULL,
CONSTRAINT PK_CASO_TESTE PRIMARY KEY (AUTOINC_CT));

/* Table: CASO_TESTE_EXECUCAO, Owner: SYSDBA */
CREATE TABLE CASO_TESTE_EXECUCAO (AUTOINC_CTE AUTOINC NOT NULL,
        DATA_CTE DATA_HORA NOT NULL,
        TEMPO_CTE DATA_HORA NOT NULL,
        STATUS_CTE SMALLINT NOT NULL,
        CASO_TESTE_CTE AUTOINC NOT NULL,
        LOG_CTE TEXTO,
        VERSAO_CTE NUMERIC(5, 2) NOT NULL,
CONSTRAINT PK_CASO_TESTE_EXECUCAO PRIMARY KEY (AUTOINC_CTE));

/* Table: FATURAMENTO_CONFIGURACAO, Owner: SYSDBA */
CREATE TABLE FATURAMENTO_CONFIGURACAO (PEDIDO_VENDA_FATCONFIG INTEGER,
        ASSISTENCIA_FATCONFIG INTEGER,
        CONSIGNACAO_FATCONFIG INTEGER,
        PEDIDO_NFCE_FATCONFIG INTEGER,
        PRODUTO_COMUM_FATCONFIG INTEGER,
        PRODUTO_ST_FATCONFIG INTEGER,
        PRODUTO_DIFERIMENTO_FATCONFIG INTEGER,
        ITEM_ASSISTENCIA_FATCONFIG INTEGER,
        QTD_FIXA_ITEM_FATCONFIG "ESTOQUE(4)",
        QTD_MAX_ITEM_FATCONFIG "ESTOQUE(4)",
        VALOR_ITEM_FIXO_FATCONFIG DINHEIRO,
        VLR_MAX_ITEM_FATCONFIG DINHEIRO,
        TRANSPORTADOR_FATCONFIG INTEGER,
        MOTORISTA_FATCONFIG INTEGER,
        TIPO_VEICULO_FATCONFIG INTEGER,
        VEICULO_FATCONFIG INTEGER,
        CLASSIFICACAO_NFCE_FATCONFIG SMALLINT,
        MODELO_NFCE_FATCONFIG SMALLINT,
        PESSOA_GERAL_FATCONFIG INTEGER,
        PESSOA_SUFRAMA_FATCONFIG INTEGER,
        PESSOA_CONSUMIDOR_FATCONFIG INTEGER,
        PESSOA_CONS_NFCE_FATCONFIG INTEGER);

/* Table: FINANCEIRO_CONFIGURACAO, Owner: SYSDBA */
CREATE TABLE FINANCEIRO_CONFIGURACAO (CLIENTE_FINCONFIG INTEGER,
        FORNECEDOR_FINCONFIG INTEGER,
        TIPO_FINCONFIG INTEGER,
        SITUACAO_FINCONFIG INTEGER,
        BANCO_FINCONFIG INTEGER,
        FORMA_PAGTO_FINCONFIG INTEGER,
        PROJETO_FINCONFIG INTEGER,
        FINANCEIRA_FINCONFIG INTEGER,
        INTERMEDIADOR_FINCONFIG INTEGER,
        GR_CONTAS_RECEBER_FINCONFIG INTEGER,
        GR_CONTAS_PAGAR_FINCONFIG INTEGER,
        VALOR_PADRAO_RECEBER_FINCONFIG NUMERIC(18, 2),
        VALOR_PADRAO_PAGAR_FINCONFIG NUMERIC(18, 2),
        CONTA_PRINCIPAL_FINCONFIG INTEGER);

/* Table: MODULO, Owner: SYSDBA */
CREATE TABLE MODULO (CODIGO_MODULO AUTOINC,
        DESCRICAO_MODULO STRING40 NOT NULL,
CONSTRAINT PK_MODULO PRIMARY KEY (CODIGO_MODULO),
CONSTRAINT UNQ1_MODULO UNIQUE (DESCRICAO_MODULO));

/* Table: PROCESSAMENTO, Owner: SYSDBA */
CREATE TABLE PROCESSAMENTO (CODIGO_PROCESSAMENTO INTEGER NOT NULL,
        DESCRICAO_PROCESSAMENTO DESCRICAO,
        CODIFICACAO_PROCESSAMENTO BLOB SUB_TYPE TEXT SEGMENT SIZE 16384 NOT NULL,
        OBSERVACAO_PROCESSAMENTO BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
        MODULO_PROCESSAMENTO AUTOINC,
CONSTRAINT PK_PROCESSAMENTO PRIMARY KEY (CODIGO_PROCESSAMENTO),
CONSTRAINT UNQ1_PROCESSAMENTO UNIQUE (DESCRICAO_PROCESSAMENTO));

/* Table: SCRIPT, Owner: SYSDBA */
CREATE TABLE SCRIPT (CODIGO_SCRIPT AUTOINC NOT NULL,
        DESCRICAO_SCRIPT STRING40 NOT NULL,
        MODULO_SCRIPT INTEGER,
        COMANDOS_SCRIPT STRING255,
CONSTRAINT PK_SCRIPT PRIMARY KEY (CODIGO_SCRIPT));

/* Table: UNIT, Owner: SYSDBA */
CREATE TABLE UNIT (CODIGO_UNIT AUTOINC NOT NULL,
        NOME_UNIT DESCRICAO,
        CODIFICACAO_UNIT BLOB SUB_TYPE TEXT SEGMENT SIZE 16384,
        OBSERVACAO_UNIT BLOB SUB_TYPE TEXT SEGMENT SIZE 100,
        MODULO_UNIT AUTOINC DEFAULT 0,
CONSTRAINT PK_UNIT PRIMARY KEY (CODIGO_UNIT),
CONSTRAINT UNQ1_UNIT UNIQUE (NOME_UNIT));

/* Table: VERSAO, Owner: SYSDBA */
CREATE TABLE VERSAO (CODIGO_VERSAO AUTOINC NOT NULL,
        DESCRICAO_VERSAO STRING40 NOT NULL,
        OBS_VERSAO BLOB SUB_TYPE TEXT SEGMENT SIZE 16384,
CONSTRAINT PK_VERSAO PRIMARY KEY (CODIGO_VERSAO));

COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

/* Stored procedures headers */
CREATE OR ALTER PROCEDURE INICIALIZA AS 
BEGIN EXIT; END ^
CREATE OR ALTER PROCEDURE VERSAO_CTRL RETURNS (VERSAO VARCHAR(5) CHARACTER SET ISO8859_1,
CODIGO INTEGER,
NUMERO INTEGER)
AS 
BEGIN SUSPEND; END ^

SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;

ALTER TABLE AREA ADD CONSTRAINT FK_AREA_1 FOREIGN KEY (MODULO_AREA) REFERENCES MODULO (CODIGO_MODULO);

ALTER TABLE CASO_TESTE ADD CONSTRAINT FK_CASO_TESTE_1 FOREIGN KEY (MODULO_CT) REFERENCES MODULO (CODIGO_MODULO);

ALTER TABLE CASO_TESTE ADD CONSTRAINT FK_CASO_TESTE_2 FOREIGN KEY (AREA_CT) REFERENCES AREA (AUTOINC_AREA);

ALTER TABLE CASO_TESTE_EXECUCAO ADD CONSTRAINT FK_CASO_TESTE_EXECUCAO_1 FOREIGN KEY (CASO_TESTE_CTE) REFERENCES CASO_TESTE (AUTOINC_CT);

ALTER TABLE UNIT ADD CONSTRAINT FK_UNIT_1 FOREIGN KEY (MODULO_UNIT) REFERENCES MODULO (CODIGO_MODULO);

COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

/* Stored procedures bodies */

ALTER PROCEDURE INICIALIZA AS 
BEGIN

  /* FATURAMENTO_CONFIGURACAO */
  IF (NOT EXISTS(SELECT 1 FROM FATURAMENTO_CONFIGURACAO)) THEN
  BEGIN
    INSERT INTO FATURAMENTO_CONFIGURACAO (
      PEDIDO_VENDA_FATCONFIG,
      ASSISTENCIA_FATCONFIG,
      CONSIGNACAO_FATCONFIG,
      PEDIDO_NFCE_FATCONFIG,
      PRODUTO_COMUM_FATCONFIG,
      PRODUTO_ST_FATCONFIG,
      PRODUTO_DIFERIMENTO_FATCONFIG,
      ITEM_ASSISTENCIA_FATCONFIG,
      QTD_FIXA_ITEM_FATCONFIG,
      QTD_MAX_ITEM_FATCONFIG,
      VALOR_ITEM_FIXO_FATCONFIG,
      VLR_MAX_ITEM_FATCONFIG,
      TRANSPORTADOR_FATCONFIG,
      MOTORISTA_FATCONFIG,
      TIPO_VEICULO_FATCONFIG,
      VEICULO_FATCONFIG,
      CLASSIFICACAO_NFCE_FATCONFIG,
      MODELO_NFCE_FATCONFIG
    ) VALUES (
      0, 0, 0, 0,
      0, 0, 0, 0,
      0, 0, 0, 0,
      0, 0, 0, 0,
      0, 0
    );
  END


  /* FINANCEIRO_CONFIGURACAO */
  IF (NOT EXISTS(SELECT 1 FROM FINANCEIRO_CONFIGURACAO)) THEN
  BEGIN
    INSERT INTO FINANCEIRO_CONFIGURACAO (
      CLIENTE_FINCONFIG,
      FORNECEDOR_FINCONFIG,
      TIPO_FINCONFIG,
      SITUACAO_FINCONFIG,
      BANCO_FINCONFIG,
      FORMA_PAGTO_FINCONFIG,
      PROJETO_FINCONFIG,
      FINANCEIRA_FINCONFIG,
      INTERMEDIADOR_FINCONFIG,
      GR_CONTAS_RECEBER_FINCONFIG,
      GR_CONTAS_PAGAR_FINCONFIG
    ) VALUES (
      0, 0, 0, 0,
      0, 0, 0, 0,
      0, 0, 0
    );
  END

END ^

ALTER PROCEDURE VERSAO_CTRL RETURNS (VERSAO VARCHAR(5) CHARACTER SET ISO8859_1,
CODIGO INTEGER,
NUMERO INTEGER)
AS 
BEGIN
  VERSAO = '0.1';
  CODIGO = 0;
  NUMERO = 1;
  SUSPEND;
END ^

SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;

/* Domain constraints */
ALTER DOMAIN LOGICO ADD CONSTRAINT
         CHECK (Value in ('S', 'N'));

/* Comments for database objects. */
COMMENT ON DOMAIN       DINHEIRO IS 'VALORES MONETARIOS';
COMMENT ON DOMAIN       ESTOQUE IS 'ESTOQUE';
COMMENT ON DOMAIN       "ESTOQUE(4)" IS 'ESTOQUE';
COMMENT ON DOMAIN       JSON IS 'TEXTO JSON';
COMMENT ON DOMAIN       LOGICO IS 'SIM ou NÃO';
COMMENT ON    COLUMN    CASO_TESTE.DESCRICAO_CASO_TESTE_CT IS 'DESCRIÇÂO DO CASO DE TESTE';
COMMENT ON    COLUMN    CASO_TESTE.ATIVO_CT IS 'CASO DE TESTE AINDA ESTA ATIVO';
COMMENT ON TABLE        CASO_TESTE_EXECUCAO IS 'REGISTRA EXECUÇÃO DOS CASOS DE TESTE.';
COMMENT ON    COLUMN    CASO_TESTE_EXECUCAO.AUTOINC_CTE IS 'AUTO INCREMENTO DO REGISTRO DE EXECUÇÃO';
COMMENT ON    COLUMN    CASO_TESTE_EXECUCAO.DATA_CTE IS 'DATA EM QUE FOI EXECUTADO O CASO DE TESTE.';
COMMENT ON    COLUMN    CASO_TESTE_EXECUCAO.TEMPO_CTE IS 'EM QUANTO TEMPO FOI EXECUTADO O CASO DE TESTE.';
COMMENT ON    COLUMN    CASO_TESTE_EXECUCAO.STATUS_CTE IS '0 - EXECUTADO COM SUCESSO
1 - ERRO EXECUÇÃO';
COMMENT ON    COLUMN    CASO_TESTE_EXECUCAO.CASO_TESTE_CTE IS 'CASO DE TESTE QUE FOI EXECUTADO';
COMMENT ON    COLUMN    CASO_TESTE_EXECUCAO.LOG_CTE IS 'Informação do erro que impediu de ser executado com sucesso.';
COMMENT ON    COLUMN    CASO_TESTE_EXECUCAO.VERSAO_CTE IS 'Versão do sistema que foi executado octet_length teste';
COMMENT ON    COLUMN    UNIT.CODIGO_UNIT IS 'AUTOINC DAS UNIT PARA TESTE BORDERO PAGAMENTO';
