/*
  Migration local do TDD_RUNNER.
  Nao executar em producao sem validacao e aprovacao explicita.
*/

SET NAMES UTF8;
SET AUTODDL OFF;

ALTER TABLE CASO_TESTE ADD REQUISITO_VERSAO VARCHAR(40) CHARACTER SET UTF8;
COMMIT WORK;

CREATE TABLE HISTORICO_EXECUCAO_TESTE (
  AUTOINC_HISTORICO INTEGER NOT NULL,
  AUTOINC_CASO_TESTE BIGINT NOT NULL,
  VERSAO_EXECUCAO VARCHAR(40) CHARACTER SET UTF8,
  REQUISITO_VERSAO VARCHAR(40) CHARACTER SET UTF8,
  STATUS_EXECUCAO VARCHAR(20) CHARACTER SET UTF8,
  ETAPA_FALHA INTEGER,
  MENSAGEM_ERRO BLOB SUB_TYPE 1 SEGMENT SIZE 100 CHARACTER SET UTF8,
  LOGS_FALHAS BLOB SUB_TYPE 1 SEGMENT SIZE 100 CHARACTER SET UTF8,
  DATA_HORA_EXECUCAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_HISTORICO_EXECUCAO_TESTE PRIMARY KEY (AUTOINC_HISTORICO),
  CONSTRAINT FK_HISTORICO_EXECUCAO_CASO FOREIGN KEY (AUTOINC_CASO_TESTE)
    REFERENCES CASO_TESTE (AUTOINC_CT)
);

CREATE TABLE METRICAS_TICK_DIFF (
  AUTOINC_METRICA_TICK_DIFF INTEGER NOT NULL,
  AUTOINC_HISTORICO INTEGER NOT NULL,
  NOME_METODO VARCHAR(120) CHARACTER SET UTF8,
  ETAPA_CASO_TESTE INTEGER,
  TEMPO_INICIO INTEGER,
  TEMPO_FIM INTEGER,
  TEMPO_TOTAL INTEGER,
  TEMPO_TOTAL_FORMATADO VARCHAR(20) CHARACTER SET UTF8,
  CONSTRAINT PK_METRICAS_TICK_DIFF PRIMARY KEY (AUTOINC_METRICA_TICK_DIFF),
  CONSTRAINT FK_METRICAS_TICK_HISTORICO FOREIGN KEY (AUTOINC_HISTORICO)
    REFERENCES HISTORICO_EXECUCAO_TESTE (AUTOINC_HISTORICO)
);

CREATE TABLE METRICAS_ASSERTS (
  AUTOINC_METRICA_ASSERTS INTEGER NOT NULL,
  AUTOINC_HISTORICO INTEGER NOT NULL,
  ETAPA_CASO_TESTE INTEGER,
  TEMPO_TOTAL INTEGER,
  ASSERTS_TOTAL INTEGER,
  ASSERTS_APROVADOS INTEGER,
  ASSERTS_FALHOS INTEGER,
  RESULTADO_ESPERADO BLOB SUB_TYPE 1 SEGMENT SIZE 100 CHARACTER SET UTF8,
  RESULTADO_OBTIDO BLOB SUB_TYPE 1 SEGMENT SIZE 100 CHARACTER SET UTF8,
  CONSTRAINT PK_METRICAS_ASSERTS PRIMARY KEY (AUTOINC_METRICA_ASSERTS),
  CONSTRAINT FK_METRICAS_ASSERTS_HISTORICO FOREIGN KEY (AUTOINC_HISTORICO)
    REFERENCES HISTORICO_EXECUCAO_TESTE (AUTOINC_HISTORICO)
);

CREATE INDEX IX_HISTORICO_EXECUCAO_CASO ON HISTORICO_EXECUCAO_TESTE (AUTOINC_CASO_TESTE);
CREATE INDEX IX_METRICAS_TICK_HISTORICO ON METRICAS_TICK_DIFF (AUTOINC_HISTORICO);
CREATE INDEX IX_METRICAS_ASSERTS_HISTORICO ON METRICAS_ASSERTS (AUTOINC_HISTORICO);
COMMIT WORK;
