name: Deploy Power Platform Solution

on:
  push:
    branches:
      - main
    paths:
      - 'src/**' # Executa apenas se houver altera es na solu o
  workflow_dispatch:

env:
  APP_ID: ${{ secrets.POWERPLATFORM_CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.POWERPLATFORM_CLIENT_SECRET }}
  TENANT_ID: ${{ secrets.POWERPLATFORM_TENANT_ID }}
  ENV_URL: ${{ secrets.POWERPLATFORM_ENV_URL }}

jobs:
  deploy:
    runs-on: windows-latest # Recomendado para usar o pac CLI nativamente
    
    steps:
      # Baixar o código do repositório para o Runner
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Power Platform CLI
        uses: microsoft/powerplatform-actions/actions-install@v1

      # Incrementar a versão do agente
      - name: Incrementar Versão da Solução
        run: |
          Write-Host "Diretório de Trabalho Atual: $env:GITHUB_WORKSPACE"
          
          $xmlPath = Join-Path $env:GITHUB_WORKSPACE "src\Other\Solution.xml"
          
          if (-not (Test-Path $xmlPath)) {
            Write-Error "ERRO CRÍTICO: O arquivo Solution.xml não foi encontrado em: $xmlPath"
            exit 1
          }
          
          [xml]$xml = Get-Content $xmlPath
          
          $runNumber = ${{ github.run_number }}
          
          $newVersion = "1.0.0.$runNumber"
          $xml.ImportExportXml.SolutionManifest.Version = $newVersion
          $xml.Save($xmlPath)
          
          $zipVersion = $newVersion -replace '\.', '_'
          echo "ZIP_VERSION=$zipVersion" >> $env:GITHUB_ENV
        shell: powershell

      - name: Empacotar Solução (Pack)
        uses: microsoft/powerplatform-actions/pack-solution@v1
        with:
          solution-folder: 'src'
          solution-file: 'DelphiTDD_Solution_${{ env.ZIP_VERSION }}.zip'
          solution-type: 'Unmanaged'

      - name: Importar Solução
        uses: microsoft/powerplatform-actions/import-solution@v1
        with:
          environment-url: ${{ env.ENV_URL }}
          app-id: ${{ env.APP_ID }}
          client-secret: ${{ env.CLIENT_SECRET }}
          tenant-id: ${{ env.TENANT_ID }}
          solution-file: DelphiTDD_Solution_${{ env.ZIP_VERSION }}.zip
          publish-changes: true
          force-overwrite: true
